### 获取当前用户余额
GET 127.0.0.1:9001/mlr/ecommerce-account-service/balance/current-balance/
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJ1c2VySWRcIjoxMixcInVzZXJuYW1lXCI6XCJtYW51QGltb29jLmNvbVwifSIsImp0aSI6Ijc5NWE2NTFjLTY0OTQtNGY5Ny1hMWIwLWNlNjZkOGFiNjhiMiIsImV4cCI6MTYzMzYxMTYwMH0.fz2eHzwobKGI7QEse7ziqd1ND3rUIy2YlnxK2lG1y9R39XV4vFxjIoKhkeBaLNatD4HEeTI9dT9p4n6CoviHgDobIBBGGmuiZbJLKFSGSFfghri5LlonytcYGq6GuA-AEFiMELJsRexvkIudoZk4crzRs_q5f6t4AxAc-QDAW3GSgtgJ60jFXRbW9gnG4h5SleEkNVlN74dMgU3eanb2bEi9pZjQ5DP9yqvdxC0YorJdyDy_rzGXbexfgsSW0VADyPgJM2HB4-V5tl8gWFfHbLdNqASKB1g6MPu_Ci9gAX8lfwvxp8c20a__qdgbA50cMxZkL0yQVWTuR0sU3qL02g


### 扣减用户余额
PUT 127.0.0.1:9001/mlr/ecommerce-account-service/balance//deduct-balance/
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJ1c2VySWRcIjoxMixcInVzZXJuYW1lXCI6XCJtYW51QGltb29jLmNvbVwifSIsImp0aSI6Ijc5NWE2NTFjLTY0OTQtNGY5Ny1hMWIwLWNlNjZkOGFiNjhiMiIsImV4cCI6MTYzMzYxMTYwMH0.fz2eHzwobKGI7QEse7ziqd1ND3rUIy2YlnxK2lG1y9R39XV4vFxjIoKhkeBaLNatD4HEeTI9dT9p4n6CoviHgDobIBBGGmuiZbJLKFSGSFfghri5LlonytcYGq6GuA-AEFiMELJsRexvkIudoZk4crzRs_q5f6t4AxAc-QDAW3GSgtgJ60jFXRbW9gnG4h5SleEkNVlN74dMgU3eanb2bEi9pZjQ5DP9yqvdxC0YorJdyDy_rzGXbexfgsSW0VADyPgJM2HB4-V5tl8gWFfHbLdNqASKB1g6MPu_Ci9gAX8lfwvxp8c20a__qdgbA50cMxZkL0yQVWTuR0sU3qL02g

{
  "userId": 12,
  "balance": 3
}