### 获取当前用户余额
GET 127.0.0.1:9001/mlr/ecommerce-account-service/balance/current-balance/
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJ1c2VySWRcIjoxMixcInVzZXJuYW1lXCI6XCJtYW51QGltb29jLmNvbVwifSIsImp0aSI6ImVkMWUzYjc4LTM0YTYtNDllNC1iNGYxLWE5Y2FlOTZiMDdlMyIsImV4cCI6MTYzMzY5ODAwMH0.Sxbs60uO4ki5aviXDp3TB99Bp0vhnF0AwYWSajAhIaiOslli2k2XhGhRnYHWp8X60NpA65J3gP6pqORFVgDnXhKqyFylZBIqW6zcksEZV_gLXDDgixLVzmvJSzEG9FmfSi0rUJpgrI6WvyXdY55M1EC7ocphkl8wEo63I7svIK96diQ1qT2jtQcd8c00nZlUzRKJQVIfuleyHLUdl71-A-uRa409VkyaYR3pfy12M3u6lCGNxlgwdJY-QMroB4ICKykbpWTONTnAYqAKeGBHHIZRMupCyHwPrTaGQ2b-_DswSGtpr2jQVsi-jCAmLaqycNWD4n5IU2gYbwwg6HlEGw


### 扣减用户余额
PUT 127.0.0.1:9001/mlr/ecommerce-account-service/balance//deduct-balance/
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJ1c2VySWRcIjoxMixcInVzZXJuYW1lXCI6XCJtYW51QGltb29jLmNvbVwifSIsImp0aSI6ImVkMWUzYjc4LTM0YTYtNDllNC1iNGYxLWE5Y2FlOTZiMDdlMyIsImV4cCI6MTYzMzY5ODAwMH0.Sxbs60uO4ki5aviXDp3TB99Bp0vhnF0AwYWSajAhIaiOslli2k2XhGhRnYHWp8X60NpA65J3gP6pqORFVgDnXhKqyFylZBIqW6zcksEZV_gLXDDgixLVzmvJSzEG9FmfSi0rUJpgrI6WvyXdY55M1EC7ocphkl8wEo63I7svIK96diQ1qT2jtQcd8c00nZlUzRKJQVIfuleyHLUdl71-A-uRa409VkyaYR3pfy12M3u6lCGNxlgwdJY-QMroB4ICKykbpWTONTnAYqAKeGBHHIZRMupCyHwPrTaGQ2b-_DswSGtpr2jQVsi-jCAmLaqycNWD4n5IU2gYbwwg6HlEGw

{
  "userId": 12,
  "balance": 3
}