### 查询服务
GET 127.0.0.1:9001/mlr/e-commerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJ1c2VySWRcIjoxMixcInVzZXJuYW1lXCI6XCJtYW51QGltb29jLmNvbVwifSIsImp0aSI6ImZjZTMzMTRhLTk5NzUtNDczMC04MzkwLTc4ZjMwMTM3NzAzNCIsImV4cCI6MTYzMzE4MzIwMH0.IUHaGigJHiDWJoQj_pLKfhrQUguWKtw7PUWSRX_mDtDgjqUPR2rsMRCU4x5m4Eb2zQH0iS456FQ_kkhsg3viJfY9Kn94ORwVGaY8SOPYBQSJsmwx6j2aLOrl8GwUtdF8sKvDBai1O9D71b3jEuTK3joS0gu436DHSh8DE21ETe6hz6Mh2i2huRE8z4DXcs81VCYmAGtDTp-UhMp18NJQY3B7rfKHEwI5lmTN2sEEnAWLPcbvMkOu1_ofsD-DTQQC4GNgaQNQm3g6lrnvvzCi_XvdMufuRRWLfIHLgswqcgKGN1HuOhFLCWQdQvQeZL6qQXElR_TcdCMG1lqVvhYIsg
token: imooc
